### ISSUE TITLE
Music Todo

### ISSUE THREAD

**Issue by JasXSL** [JasXSL/FetishQuest#4]
I've been thinking about different soundtracks for certain areas or encounters in the game. Each track should probably have an ambient and a combat version.

Comment below if you want to claim one. See the wiki on how to set it up: https://wiki.fetishquest.com/index.php?title=Creating_Music

Areas
- [x] Forest
- [ ] Port: Something sailory
- [ ] Cave: Something with lots of echo
- [ ] Demons: ???
- [ ] Skeletal: Needs trombones and xylophones
- [ ] Village: Something relaxed
- [ ] Inn: Something upbeat
- [ ] Holy: Organs and choir?
- [ ] Sewers: ???
- [ ] Bog: Banjos.
- [ ] Upperclass: Harpsichord and violins
- [ ] Spooky: 
- [ ] Underwater: Rhodes probably
- [ ] Farm: Acoustic guitar, country-elements?

Specific areas
- [ ] Yuug city: Regal, lots of brass.
- [x] West portswood
- [ ] Tentacle wrestling: Porn guitars?
- [ ] Should Chad have his own theme?
- [ ] Main menu theme?

Cues

- [ ] Battle won
- [ ] Battle lost
- [ ] Sleep
